-- ============================================================================
-- Kantu Market - Poblacion de datos demo (catalogo grande para demostracion)
-- ============================================================================
--
-- GENERADO automaticamente. No editar a mano: cambiar el generador y regenerar.
--
-- Crea 4 empresas + 4 tiendas + clientes, con categorias, productos (15+ por
-- tienda) y variantes. No depende de Cloudinary (imagenes = picsum.photos).
--
-- Requisitos: migraciones aplicadas (python manage.py migrate). Los roles
-- semilla ya existen por usuarios/0002_roles_semilla.
--
-- Ejecucion (ajustar segun tu .env):
--   psql -h localhost -U postgres -d kantu_market -f seed_empresas.sql
--
-- Re-ejecutable: primero hace un reset del catalogo de las 4 tiendas demo
-- (paso 0) y luego re-inserta todo. Usuarios y tiendas se mantienen por
-- clave natural (email / slug). El archivo es 100% ASCII a proposito.
--
-- Credenciales de todos los usuarios demo:  Password123!
--   empresa1@kantu.bo  -> Textiles Los Andes     (textiles-los-andes)
--   empresa2@kantu.bo  -> Sabores de Bolivia     (sabores-de-bolivia)
--   empresa3@kantu.bo  -> Tecno Oriente          (tecno-oriente)
--   empresa4@kantu.bo  -> Ceramica Tiwanaku      (ceramica-tiwanaku)
--   cliente1@kantu.bo, cliente2@kantu.bo, cliente3@kantu.bo, cliente4@kantu.bo, cliente5@kantu.bo, cliente6@kantu.bo
-- ============================================================================

SET client_encoding TO 'UTF8';

BEGIN;

-- 0. Reset determinista del catalogo demo.
--    Solo toca las 4 tiendas demo; NO borra usuarios ni las tiendas.
--    Si algun DELETE falla por FK es que hay datos reales (pedidos, resenas,
--    eventos IA) sobre el catalogo demo: revisar antes de continuar.
DELETE FROM item_carrito WHERE variante_id IN (
     SELECT v.id FROM variante v
     JOIN producto p ON p.id = v.producto_id
     JOIN tienda t ON t.id = p.tienda_id
     WHERE t.slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku'));
DELETE FROM item_pedido  WHERE variante_id IN (
     SELECT v.id FROM variante v
     JOIN producto p ON p.id = v.producto_id
     JOIN tienda t ON t.id = p.tienda_id
     WHERE t.slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku'));
DELETE FROM variante WHERE producto_id IN (
     SELECT p.id FROM producto p JOIN tienda t ON t.id = p.tienda_id
     WHERE t.slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku'));
DELETE FROM producto WHERE tienda_id IN (SELECT id FROM tienda WHERE slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku'));
DELETE FROM categoria WHERE tienda_id IN (SELECT id FROM tienda WHERE slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku'));
DELETE FROM direccion_tienda WHERE tienda_id IN (SELECT id FROM tienda WHERE slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku'));

-- 1. Usuarios (4 empresas + 6 clientes). Hash = 'Password123!'.
INSERT INTO usuario
    (password, is_superuser, first_name, last_name, is_staff, is_active,
     date_joined, email, fecha_registro, activo, rol_id)
SELECT
    'pbkdf2_sha256$870000$KcLpbH6MM9wGs6RPDjxWbD$7p/ETMzaYAKjYYsXm5F6O4vZpT7fEvtURZSnr20DT6U=',
    false, d.first_name, d.last_name, false, true,
    now(), d.email, now(), true,
    (SELECT id FROM rol WHERE nombre = d.rol)
FROM (VALUES
    ('Maria', 'Condori', 'empresa1@kantu.bo', 'empresa'),
    ('Jorge', 'Vargas', 'empresa2@kantu.bo', 'empresa'),
    ('Rosa', 'Flores', 'empresa3@kantu.bo', 'empresa'),
    ('David', 'Mamani', 'empresa4@kantu.bo', 'empresa'),
    ('Lucia', 'Rojas', 'cliente1@kantu.bo', 'cliente'),
    ('Pedro', 'Gutierrez', 'cliente2@kantu.bo', 'cliente'),
    ('Carla', 'Ticona', 'cliente3@kantu.bo', 'cliente'),
    ('Marco', 'Antezana', 'cliente4@kantu.bo', 'cliente'),
    ('Elena', 'Choque', 'cliente5@kantu.bo', 'cliente'),
    ('Ruben', 'Salazar', 'cliente6@kantu.bo', 'cliente')
) AS d(first_name, last_name, email, rol)
WHERE NOT EXISTS (SELECT 1 FROM usuario u WHERE u.email = d.email);

-- 2. Tiendas (una por empresa)
INSERT INTO tienda
    (nombre, slug, logo_url, color_primario, descripcion, fecha_creacion,
     activa, propietario_id)
SELECT
    d.nombre, d.slug, '', d.color, d.descripcion, now(), true,
    (SELECT id FROM usuario WHERE email = d.owner_email)
FROM (VALUES
    ('Textiles Los Andes', 'textiles-los-andes', '#C8102E',
     'Aguayos, ponchos, chompas y accesorios tejidos a mano en La Paz con lana de alpaca y oveja.',
     'empresa1@kantu.bo'),
    ('Sabores de Bolivia', 'sabores-de-bolivia', '#27AE60',
     'Cafe de altura, chocolate de cacao boliviano, infusiones y snacks andinos desde Cochabamba.',
     'empresa2@kantu.bo'),
    ('Tecno Oriente', 'tecno-oriente', '#2E86C1',
     'Accesorios, audio, cargadores y gadgets para tu celular. Tienda crucena con envios a todo el pais.',
     'empresa3@kantu.bo'),
    ('Ceramica Tiwanaku', 'ceramica-tiwanaku', '#A04000',
     'Vajilla, macetas, iluminacion y piezas decorativas de ceramica trabajadas y pintadas a mano en El Alto.',
     'empresa4@kantu.bo')
) AS d(nombre, slug, color, descripcion, owner_email)
WHERE NOT EXISTS (SELECT 1 FROM tienda t WHERE t.slug = d.slug);

-- 3. Vinculo propietario <-> tienda
INSERT INTO usuario_tienda (rol_interno, fecha_asignacion, tienda_id, usuario_id)
SELECT 'propietario', now(), t.id, t.propietario_id
FROM tienda t
WHERE t.slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku')
  AND NOT EXISTS (
      SELECT 1 FROM usuario_tienda ut
      WHERE ut.tienda_id = t.id AND ut.usuario_id = t.propietario_id
  );

-- 4. Direcciones de tienda
INSERT INTO direccion_tienda (direccion, ciudad, telefono, tienda_id)
SELECT d.direccion, d.ciudad, d.telefono,
       (SELECT id FROM tienda WHERE slug = d.slug)
FROM (VALUES
    ('textiles-los-andes', 'Calle Sagarnaga 245', 'La Paz', '+591 71234567'),
    ('sabores-de-bolivia', 'Av. America 1500', 'Cochabamba', '+591 72345678'),
    ('tecno-oriente', 'Av. Monsenor Rivero 300', 'Santa Cruz', '+591 73456789'),
    ('ceramica-tiwanaku', 'Ceja de El Alto, Calle 2', 'El Alto', '+591 74567890')
) AS d(slug, direccion, ciudad, telefono)
WHERE NOT EXISTS (
    SELECT 1 FROM direccion_tienda dt
    WHERE dt.tienda_id = (SELECT id FROM tienda WHERE slug = d.slug)
);

-- 5. Categorias (por tienda)
INSERT INTO categoria (nombre, categoria_padre_id, tienda_id)
SELECT d.nombre, NULL, (SELECT id FROM tienda WHERE slug = d.slug)
FROM (VALUES
    ('textiles-los-andes', 'Aguayos'),
    ('textiles-los-andes', 'Ponchos'),
    ('textiles-los-andes', 'Chalinas'),
    ('textiles-los-andes', 'Chompas'),
    ('textiles-los-andes', 'Gorros'),
    ('textiles-los-andes', 'Accesorios'),
    ('textiles-los-andes', 'Bolsos'),
    ('textiles-los-andes', 'Hogar'),
    ('sabores-de-bolivia', 'Cafes'),
    ('sabores-de-bolivia', 'Chocolates'),
    ('sabores-de-bolivia', 'Infusiones'),
    ('sabores-de-bolivia', 'Snacks'),
    ('sabores-de-bolivia', 'Despensa'),
    ('tecno-oriente', 'Fundas'),
    ('tecno-oriente', 'Proteccion'),
    ('tecno-oriente', 'Audio'),
    ('tecno-oriente', 'Energia'),
    ('tecno-oriente', 'Cables'),
    ('tecno-oriente', 'Almacenamiento'),
    ('tecno-oriente', 'Wearables'),
    ('tecno-oriente', 'Accesorios'),
    ('tecno-oriente', 'Gaming'),
    ('tecno-oriente', 'Hogar'),
    ('ceramica-tiwanaku', 'Vajilla'),
    ('ceramica-tiwanaku', 'Tazas y jarros'),
    ('ceramica-tiwanaku', 'Decoracion'),
    ('ceramica-tiwanaku', 'Floreros'),
    ('ceramica-tiwanaku', 'Macetas'),
    ('ceramica-tiwanaku', 'Iluminacion'),
    ('ceramica-tiwanaku', 'Utensilios'),
    ('ceramica-tiwanaku', 'Aromas')
) AS d(slug, nombre)
WHERE NOT EXISTS (
    SELECT 1 FROM categoria c
    WHERE c.tienda_id = (SELECT id FROM tienda WHERE slug = d.slug)
      AND c.nombre = d.nombre
);

-- 6. Productos (imagenes: placeholder de picsum.photos)
INSERT INTO producto
    (nombre, descripcion, activo, categoria_id, tienda_id, slug,
     etiquetas, imagenes, creado, actualizado)
SELECT
    d.nombre, d.descripcion, true,
    (SELECT c.id FROM categoria c
       WHERE c.tienda_id = (SELECT id FROM tienda WHERE slug = d.slug)
         AND c.nombre = d.categoria
       LIMIT 1),
    (SELECT id FROM tienda WHERE slug = d.slug),
    d.pslug,
    string_to_array(d.etiquetas, ',')::varchar(50)[],
    ('[{"url": "https://picsum.photos/seed/' || d.pslug ||
        '/600/600", "public_id": "seed/' || d.pslug || '"}]')::jsonb,
    now(), now()
FROM (VALUES
    ('textiles-los-andes', 'Aguayos', 'Aguayo tradicional paceno',
     'aguayo-tradicional-paceno',
     'Aguayo tradicional paceno. Tejido a mano en La Paz con fibras naturales.',
     'aguayo,tejido,artesanal'),
    ('textiles-los-andes', 'Aguayos', 'Aguayo grande multicolor',
     'aguayo-grande-multicolor',
     'Aguayo grande multicolor. Tejido a mano en La Paz con fibras naturales.',
     'aguayo,telar,artesanal'),
    ('textiles-los-andes', 'Aguayos', 'Aguayo ceremonial rojo',
     'aguayo-ceremonial-rojo',
     'Aguayo ceremonial rojo. Tejido a mano en La Paz con fibras naturales.',
     'aguayo,ceremonial'),
    ('textiles-los-andes', 'Aguayos', 'Q''ipina para cargar',
     'q-ipina-para-cargar',
     'Q''ipina para cargar. Tejido a mano en La Paz con fibras naturales.',
     'aguayo,portabebe'),
    ('textiles-los-andes', 'Ponchos', 'Poncho de alpaca cafe',
     'poncho-de-alpaca-cafe',
     'Poncho de alpaca cafe. Tejido a mano en La Paz con fibras naturales.',
     'poncho,alpaca,abrigo'),
    ('textiles-los-andes', 'Ponchos', 'Poncho de lana gris',
     'poncho-de-lana-gris',
     'Poncho de lana gris. Tejido a mano en La Paz con fibras naturales.',
     'poncho,lana'),
    ('textiles-los-andes', 'Ponchos', 'Poncho impermeable andino',
     'poncho-impermeable-andino',
     'Poncho impermeable andino. Tejido a mano en La Paz con fibras naturales.',
     'poncho,impermeable'),
    ('textiles-los-andes', 'Chalinas', 'Chalina de alpaca',
     'chalina-de-alpaca',
     'Chalina de alpaca. Tejido a mano en La Paz con fibras naturales.',
     'chalina,alpaca,accesorio'),
    ('textiles-los-andes', 'Chalinas', 'Chalina de baby alpaca',
     'chalina-de-baby-alpaca',
     'Chalina de baby alpaca. Tejido a mano en La Paz con fibras naturales.',
     'chalina,baby-alpaca'),
    ('textiles-los-andes', 'Chalinas', 'Bufanda tejida a crochet',
     'bufanda-tejida-a-crochet',
     'Bufanda tejida a crochet. Tejido a mano en La Paz con fibras naturales.',
     'bufanda,crochet'),
    ('textiles-los-andes', 'Chompas', 'Chompa jacquard andina',
     'chompa-jacquard-andina',
     'Chompa jacquard andina. Tejido a mano en La Paz con fibras naturales.',
     'chompa,jacquard'),
    ('textiles-los-andes', 'Chompas', 'Chompa de alpaca cuello alto',
     'chompa-de-alpaca-cuello-alto',
     'Chompa de alpaca cuello alto. Tejido a mano en La Paz con fibras naturales.',
     'chompa,alpaca'),
    ('textiles-los-andes', 'Chompas', 'Cardigan de lana natural',
     'cardigan-de-lana-natural',
     'Cardigan de lana natural. Tejido a mano en La Paz con fibras naturales.',
     'cardigan,lana'),
    ('textiles-los-andes', 'Gorros', 'Gorro chullo con orejeras',
     'gorro-chullo-con-orejeras',
     'Gorro chullo con orejeras. Tejido a mano en La Paz con fibras naturales.',
     'gorro,chullo'),
    ('textiles-los-andes', 'Gorros', 'Gorro de alpaca con pompon',
     'gorro-de-alpaca-con-pompon',
     'Gorro de alpaca con pompon. Tejido a mano en La Paz con fibras naturales.',
     'gorro,alpaca'),
    ('textiles-los-andes', 'Gorros', 'Vincha tejida andina',
     'vincha-tejida-andina',
     'Vincha tejida andina. Tejido a mano en La Paz con fibras naturales.',
     'vincha,accesorio'),
    ('textiles-los-andes', 'Accesorios', 'Guantes de lana tejidos',
     'guantes-de-lana-tejidos',
     'Guantes de lana tejidos. Tejido a mano en La Paz con fibras naturales.',
     'guantes,lana'),
    ('textiles-los-andes', 'Accesorios', 'Medias de alpaca gruesas',
     'medias-de-alpaca-gruesas',
     'Medias de alpaca gruesas. Tejido a mano en La Paz con fibras naturales.',
     'medias,alpaca'),
    ('textiles-los-andes', 'Bolsos', 'Bolso tejido a mano',
     'bolso-tejido-a-mano',
     'Bolso tejido a mano. Tejido a mano en La Paz con fibras naturales.',
     'bolso,tejido'),
    ('textiles-los-andes', 'Bolsos', 'Mochila andina de aguayo',
     'mochila-andina-de-aguayo',
     'Mochila andina de aguayo. Tejido a mano en La Paz con fibras naturales.',
     'mochila,aguayo'),
    ('textiles-los-andes', 'Bolsos', 'Monedero de aguayo',
     'monedero-de-aguayo',
     'Monedero de aguayo. Tejido a mano en La Paz con fibras naturales.',
     'monedero,aguayo'),
    ('textiles-los-andes', 'Hogar', 'Tapiz decorativo de pared',
     'tapiz-decorativo-de-pared',
     'Tapiz decorativo de pared. Tejido a mano en La Paz con fibras naturales.',
     'tapiz,decoracion'),
    ('textiles-los-andes', 'Hogar', 'Camino de mesa andino',
     'camino-de-mesa-andino',
     'Camino de mesa andino. Tejido a mano en La Paz con fibras naturales.',
     'mantel,hogar'),
    ('sabores-de-bolivia', 'Cafes', 'Cafe de altura Yungas 250g',
     'cafe-de-altura-yungas-250g',
     'Cafe de altura Yungas 250g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'cafe,yungas,arabica'),
    ('sabores-de-bolivia', 'Cafes', 'Cafe organico Caranavi 500g',
     'cafe-organico-caranavi-500g',
     'Cafe organico Caranavi 500g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'cafe,organico'),
    ('sabores-de-bolivia', 'Cafes', 'Cafe en grano espresso 1kg',
     'cafe-en-grano-espresso-1kg',
     'Cafe en grano espresso 1kg. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'cafe,espresso'),
    ('sabores-de-bolivia', 'Cafes', 'Cafe descafeinado 250g',
     'cafe-descafeinado-250g',
     'Cafe descafeinado 250g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'cafe,descafeinado'),
    ('sabores-de-bolivia', 'Cafes', 'Capsulas de cafe compatibles x10',
     'capsulas-de-cafe-compatibles-x10',
     'Capsulas de cafe compatibles x10. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'cafe,capsulas'),
    ('sabores-de-bolivia', 'Cafes', 'Cafe soluble frasco 170g',
     'cafe-soluble-frasco-170g',
     'Cafe soluble frasco 170g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'cafe,soluble'),
    ('sabores-de-bolivia', 'Chocolates', 'Chocolate 70% cacao boliviano',
     'chocolate-70-cacao-boliviano',
     'Chocolate 70% cacao boliviano. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'chocolate,cacao'),
    ('sabores-de-bolivia', 'Chocolates', 'Chocolate con leche y quinua',
     'chocolate-con-leche-y-quinua',
     'Chocolate con leche y quinua. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'chocolate,quinua'),
    ('sabores-de-bolivia', 'Chocolates', 'Chocolate 100% cacao Alto Beni',
     'chocolate-100-cacao-alto-beni',
     'Chocolate 100% cacao Alto Beni. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'chocolate,puro'),
    ('sabores-de-bolivia', 'Chocolates', 'Cocoa en polvo 200g',
     'cocoa-en-polvo-200g',
     'Cocoa en polvo 200g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'cocoa,reposteria'),
    ('sabores-de-bolivia', 'Chocolates', 'Bombones surtidos caja x12',
     'bombones-surtidos-caja-x12',
     'Bombones surtidos caja x12. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'bombones,regalo'),
    ('sabores-de-bolivia', 'Infusiones', 'Mate de coca en bolsitas x25',
     'mate-de-coca-en-bolsitas-x25',
     'Mate de coca en bolsitas x25. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'mate,coca,infusion'),
    ('sabores-de-bolivia', 'Infusiones', 'Te de manzanilla andina x25',
     'te-de-manzanilla-andina-x25',
     'Te de manzanilla andina x25. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'te,manzanilla'),
    ('sabores-de-bolivia', 'Infusiones', 'Infusion de muna 40g',
     'infusion-de-muna-40g',
     'Infusion de muna 40g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'muna,digestivo'),
    ('sabores-de-bolivia', 'Infusiones', 'Anis de campo 40g',
     'anis-de-campo-40g',
     'Anis de campo 40g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'anis,infusion'),
    ('sabores-de-bolivia', 'Snacks', 'Quinua pop con miel 80g',
     'quinua-pop-con-miel-80g',
     'Quinua pop con miel 80g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'quinua,snack'),
    ('sabores-de-bolivia', 'Snacks', 'Barras de amaranto x6',
     'barras-de-amaranto-x6',
     'Barras de amaranto x6. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'amaranto,barra'),
    ('sabores-de-bolivia', 'Snacks', 'Mani tostado con sal 200g',
     'mani-tostado-con-sal-200g',
     'Mani tostado con sal 200g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'mani,snack'),
    ('sabores-de-bolivia', 'Snacks', 'Habas fritas picantes 150g',
     'habas-fritas-picantes-150g',
     'Habas fritas picantes 150g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'habas,picante'),
    ('sabores-de-bolivia', 'Snacks', 'Chips de camote 120g',
     'chips-de-camote-120g',
     'Chips de camote 120g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'camote,chips'),
    ('sabores-de-bolivia', 'Snacks', 'Tostado de maiz willkaparu 250g',
     'tostado-de-maiz-willkaparu-250g',
     'Tostado de maiz willkaparu 250g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'maiz,tostado'),
    ('sabores-de-bolivia', 'Despensa', 'Miel de abeja pura 500g',
     'miel-de-abeja-pura-500g',
     'Miel de abeja pura 500g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'miel,natural'),
    ('sabores-de-bolivia', 'Despensa', 'Azucar de cana integral 1kg',
     'azucar-de-cana-integral-1kg',
     'Azucar de cana integral 1kg. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'azucar,cana'),
    ('sabores-de-bolivia', 'Despensa', 'Sal rosada de Uyuni 250g',
     'sal-rosada-de-uyuni-250g',
     'Sal rosada de Uyuni 250g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'sal,uyuni'),
    ('sabores-de-bolivia', 'Despensa', 'Aji amarillo molido 100g',
     'aji-amarillo-molido-100g',
     'Aji amarillo molido 100g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'aji,condimento'),
    ('sabores-de-bolivia', 'Despensa', 'Quinua real blanca 1kg',
     'quinua-real-blanca-1kg',
     'Quinua real blanca 1kg. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'quinua,grano'),
    ('sabores-de-bolivia', 'Despensa', 'Chia organica 250g',
     'chia-organica-250g',
     'Chia organica 250g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'chia,superalimento'),
    ('sabores-de-bolivia', 'Despensa', 'Canahua en hojuelas 400g',
     'canahua-en-hojuelas-400g',
     'Canahua en hojuelas 400g. Producto boliviano seleccionado, ideal para regalo o consumo diario.',
     'canahua,cereal'),
    ('tecno-oriente', 'Fundas', 'Funda de silicona para celular',
     'funda-de-silicona-para-celular',
     'Funda de silicona para celular. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'funda,silicona'),
    ('tecno-oriente', 'Fundas', 'Funda transparente antishock',
     'funda-transparente-antishock',
     'Funda transparente antishock. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'funda,antishock'),
    ('tecno-oriente', 'Fundas', 'Funda tipo cartera con tarjetero',
     'funda-tipo-cartera-con-tarjetero',
     'Funda tipo cartera con tarjetero. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'funda,cartera'),
    ('tecno-oriente', 'Proteccion', 'Vidrio templado 9H',
     'vidrio-templado-9h',
     'Vidrio templado 9H. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'vidrio,proteccion'),
    ('tecno-oriente', 'Proteccion', 'Protector de camara de vidrio',
     'protector-de-camara-de-vidrio',
     'Protector de camara de vidrio. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'camara,proteccion'),
    ('tecno-oriente', 'Audio', 'Audifonos inalambricos TWS',
     'audifonos-inalambricos-tws',
     'Audifonos inalambricos TWS. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'audifonos,bluetooth,tws'),
    ('tecno-oriente', 'Audio', 'Audifonos con cable y microfono',
     'audifonos-con-cable-y-microfono',
     'Audifonos con cable y microfono. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'audifonos,cable'),
    ('tecno-oriente', 'Audio', 'Audifonos deportivos con gancho',
     'audifonos-deportivos-con-gancho',
     'Audifonos deportivos con gancho. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'audifonos,deporte'),
    ('tecno-oriente', 'Audio', 'Parlante bluetooth portatil',
     'parlante-bluetooth-portatil',
     'Parlante bluetooth portatil. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'parlante,bluetooth'),
    ('tecno-oriente', 'Audio', 'Parlante bluetooth resistente al agua',
     'parlante-bluetooth-resistente-al-agua',
     'Parlante bluetooth resistente al agua. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'parlante,ipx7'),
    ('tecno-oriente', 'Audio', 'Microfono lavalier para celular',
     'microfono-lavalier-para-celular',
     'Microfono lavalier para celular. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'microfono,creador'),
    ('tecno-oriente', 'Energia', 'Cargador rapido USB-C 20W',
     'cargador-rapido-usb-c-20w',
     'Cargador rapido USB-C 20W. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'cargador,usbc'),
    ('tecno-oriente', 'Energia', 'Cargador de auto doble puerto',
     'cargador-de-auto-doble-puerto',
     'Cargador de auto doble puerto. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'cargador,auto'),
    ('tecno-oriente', 'Energia', 'Power bank 10000mAh',
     'power-bank-10000mah',
     'Power bank 10000mAh. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'powerbank,bateria'),
    ('tecno-oriente', 'Energia', 'Power bank 20000mAh carga rapida',
     'power-bank-20000mah-carga-rapida',
     'Power bank 20000mAh carga rapida. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'powerbank,pd'),
    ('tecno-oriente', 'Energia', 'Cargador inalambrico 15W',
     'cargador-inalambrico-15w',
     'Cargador inalambrico 15W. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'cargador,qi'),
    ('tecno-oriente', 'Cables', 'Cable USB-C a USB-C 1m',
     'cable-usb-c-a-usb-c-1m',
     'Cable USB-C a USB-C 1m. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'cable,usbc'),
    ('tecno-oriente', 'Cables', 'Cable Lightning trenzado 2m',
     'cable-lightning-trenzado-2m',
     'Cable Lightning trenzado 2m. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'cable,lightning'),
    ('tecno-oriente', 'Cables', 'Cable USB-C a HDMI 4K',
     'cable-usb-c-a-hdmi-4k',
     'Cable USB-C a HDMI 4K. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'cable,hdmi'),
    ('tecno-oriente', 'Almacenamiento', 'Memoria USB 64GB',
     'memoria-usb-64gb',
     'Memoria USB 64GB. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'usb,almacenamiento'),
    ('tecno-oriente', 'Almacenamiento', 'MicroSD 128GB clase 10',
     'microsd-128gb-clase-10',
     'MicroSD 128GB clase 10. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'microsd,almacenamiento'),
    ('tecno-oriente', 'Almacenamiento', 'Hub USB-C 6 en 1',
     'hub-usb-c-6-en-1',
     'Hub USB-C 6 en 1. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'hub,usbc'),
    ('tecno-oriente', 'Wearables', 'Smartwatch deportivo',
     'smartwatch-deportivo',
     'Smartwatch deportivo. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'smartwatch,fitness'),
    ('tecno-oriente', 'Wearables', 'Banda de actividad fisica',
     'banda-de-actividad-fisica',
     'Banda de actividad fisica. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'smartband,fitness'),
    ('tecno-oriente', 'Accesorios', 'Soporte de celular para auto',
     'soporte-de-celular-para-auto',
     'Soporte de celular para auto. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'soporte,auto'),
    ('tecno-oriente', 'Accesorios', 'Aro de luz LED 10 pulgadas',
     'aro-de-luz-led-10-pulgadas',
     'Aro de luz LED 10 pulgadas. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'aro-luz,creador'),
    ('tecno-oriente', 'Accesorios', 'Tripode flexible para celular',
     'tripode-flexible-para-celular',
     'Tripode flexible para celular. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'tripode,foto'),
    ('tecno-oriente', 'Gaming', 'Gamepad bluetooth',
     'gamepad-bluetooth',
     'Gamepad bluetooth. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'gamepad,gaming'),
    ('tecno-oriente', 'Gaming', 'Mouse inalambrico',
     'mouse-inalambrico',
     'Mouse inalambrico. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'mouse,pc'),
    ('tecno-oriente', 'Gaming', 'Teclado bluetooth compacto',
     'teclado-bluetooth-compacto',
     'Teclado bluetooth compacto. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'teclado,pc'),
    ('tecno-oriente', 'Hogar', 'Foco inteligente WiFi RGB',
     'foco-inteligente-wifi-rgb',
     'Foco inteligente WiFi RGB. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'foco,smart-home'),
    ('tecno-oriente', 'Hogar', 'Enchufe inteligente WiFi',
     'enchufe-inteligente-wifi',
     'Enchufe inteligente WiFi. Accesorio con garantia de 3 meses y envios a todo el pais.',
     'enchufe,smart-home'),
    ('ceramica-tiwanaku', 'Vajilla', 'Juego de tazas andinas x4',
     'juego-de-tazas-andinas-x4',
     'Juego de tazas andinas x4. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'tazas,vajilla'),
    ('ceramica-tiwanaku', 'Vajilla', 'Juego de platos esmaltados x6',
     'juego-de-platos-esmaltados-x6',
     'Juego de platos esmaltados x6. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'platos,vajilla'),
    ('ceramica-tiwanaku', 'Vajilla', 'Bowl de ceramica rustica',
     'bowl-de-ceramica-rustica',
     'Bowl de ceramica rustica. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'bowl,vajilla'),
    ('ceramica-tiwanaku', 'Vajilla', 'Ensaladera grande pintada',
     'ensaladera-grande-pintada',
     'Ensaladera grande pintada. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'ensaladera,vajilla'),
    ('ceramica-tiwanaku', 'Vajilla', 'Fuente ovalada para horno',
     'fuente-ovalada-para-horno',
     'Fuente ovalada para horno. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'fuente,horno'),
    ('ceramica-tiwanaku', 'Tazas y jarros', 'Jarra de agua 1.5L',
     'jarra-de-agua-1-5l',
     'Jarra de agua 1.5L. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'jarra,mesa'),
    ('ceramica-tiwanaku', 'Tazas y jarros', 'Set de jarro y vasos x4',
     'set-de-jarro-y-vasos-x4',
     'Set de jarro y vasos x4. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'jarro,vasos'),
    ('ceramica-tiwanaku', 'Tazas y jarros', 'Taza mug artesanal',
     'taza-mug-artesanal',
     'Taza mug artesanal. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'taza,mug'),
    ('ceramica-tiwanaku', 'Tazas y jarros', 'Taza espresso x2',
     'taza-espresso-x2',
     'Taza espresso x2. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'taza,espresso'),
    ('ceramica-tiwanaku', 'Tazas y jarros', 'Chop cervecero de ceramica',
     'chop-cervecero-de-ceramica',
     'Chop cervecero de ceramica. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'chop,cerveza'),
    ('ceramica-tiwanaku', 'Decoracion', 'Plato decorativo Tiwanaku',
     'plato-decorativo-tiwanaku',
     'Plato decorativo Tiwanaku. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'plato,decoracion'),
    ('ceramica-tiwanaku', 'Decoracion', 'Cuadro ceramico Puerta del Sol',
     'cuadro-ceramico-puerta-del-sol',
     'Cuadro ceramico Puerta del Sol. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'cuadro,tiwanaku'),
    ('ceramica-tiwanaku', 'Decoracion', 'Figura de chakana',
     'figura-de-chakana',
     'Figura de chakana. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'chakana,decoracion'),
    ('ceramica-tiwanaku', 'Decoracion', 'Portavelas de ceramica x3',
     'portavelas-de-ceramica-x3',
     'Portavelas de ceramica x3. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'portavelas,decoracion'),
    ('ceramica-tiwanaku', 'Decoracion', 'Campana de viento de ceramica',
     'campana-de-viento-de-ceramica',
     'Campana de viento de ceramica. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'campana,jardin'),
    ('ceramica-tiwanaku', 'Floreros', 'Florero de ceramica esmaltada',
     'florero-de-ceramica-esmaltada',
     'Florero de ceramica esmaltada. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'florero,decoracion'),
    ('ceramica-tiwanaku', 'Floreros', 'Florero alto minimalista',
     'florero-alto-minimalista',
     'Florero alto minimalista. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'florero,minimalista'),
    ('ceramica-tiwanaku', 'Floreros', 'Set de 3 mini floreros',
     'set-de-3-mini-floreros',
     'Set de 3 mini floreros. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'florero,set'),
    ('ceramica-tiwanaku', 'Macetas', 'Maceta de barro pintada a mano',
     'maceta-de-barro-pintada-a-mano',
     'Maceta de barro pintada a mano. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'maceta,barro'),
    ('ceramica-tiwanaku', 'Macetas', 'Maceta colgante trenzada',
     'maceta-colgante-trenzada',
     'Maceta colgante trenzada. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'maceta,colgante'),
    ('ceramica-tiwanaku', 'Macetas', 'Set de macetas pequenas x3',
     'set-de-macetas-pequenas-x3',
     'Set de macetas pequenas x3. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'maceta,set'),
    ('ceramica-tiwanaku', 'Macetas', 'Maceta grande para exterior',
     'maceta-grande-para-exterior',
     'Maceta grande para exterior. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'maceta,exterior'),
    ('ceramica-tiwanaku', 'Iluminacion', 'Lampara de mesa de ceramica',
     'lampara-de-mesa-de-ceramica',
     'Lampara de mesa de ceramica. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'lampara,iluminacion'),
    ('ceramica-tiwanaku', 'Iluminacion', 'Aplique de pared artesanal',
     'aplique-de-pared-artesanal',
     'Aplique de pared artesanal. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'aplique,iluminacion'),
    ('ceramica-tiwanaku', 'Utensilios', 'Individuales de ceramica x4',
     'individuales-de-ceramica-x4',
     'Individuales de ceramica x4. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'individuales,mesa'),
    ('ceramica-tiwanaku', 'Utensilios', 'Salero y pimentero',
     'salero-y-pimentero',
     'Salero y pimentero. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'salero,mesa'),
    ('ceramica-tiwanaku', 'Utensilios', 'Aceitera de ceramica',
     'aceitera-de-ceramica',
     'Aceitera de ceramica. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'aceitera,cocina'),
    ('ceramica-tiwanaku', 'Utensilios', 'Mortero de piedra volcanica',
     'mortero-de-piedra-volcanica',
     'Mortero de piedra volcanica. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'mortero,cocina'),
    ('ceramica-tiwanaku', 'Aromas', 'Difusor de aromas de ceramica',
     'difusor-de-aromas-de-ceramica',
     'Difusor de aromas de ceramica. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'difusor,aromas'),
    ('ceramica-tiwanaku', 'Aromas', 'Quemador de incienso artesanal',
     'quemador-de-incienso-artesanal',
     'Quemador de incienso artesanal. Pieza de ceramica trabajada y pintada a mano en El Alto.',
     'incienso,aromas')
) AS d(slug, categoria, nombre, pslug, descripcion, etiquetas)
WHERE NOT EXISTS (
    SELECT 1 FROM producto p
    WHERE p.tienda_id = (SELECT id FROM tienda WHERE slug = d.slug)
      AND p.slug = d.pslug
);

-- 7. Variantes (incluye precio_oferta, multi-variante y stock 0 / bajo)
INSERT INTO variante
    (nombre, sku, producto_id, precio, precio_oferta, stock, stock_minimo,
     atributos, activa)
SELECT
    d.vnombre, d.sku,
    (SELECT p.id FROM producto p
       WHERE p.tienda_id = (SELECT id FROM tienda WHERE slug = d.slug)
         AND p.slug = d.pslug
       LIMIT 1),
    d.precio::numeric, d.precio_oferta::numeric, d.stock, d.stock_minimo,
    d.atributos::jsonb, true
FROM (VALUES
    ('textiles-los-andes', 'aguayo-tradicional-paceno', 'Unica', 'TLA-001', 180.00, NULL, 40, 5, '{}'),
    ('textiles-los-andes', 'aguayo-grande-multicolor', 'Unica', 'TLA-002', 240.00, NULL, 8, 3, '{}'),
    ('textiles-los-andes', 'aguayo-ceremonial-rojo', 'Unica', 'TLA-003', 320.00, 272.00, 0, 3, '{}'),
    ('textiles-los-andes', 'q-ipina-para-cargar', 'Unica', 'TLA-004', 150.00, NULL, 25, 5, '{}'),
    ('textiles-los-andes', 'poncho-de-alpaca-cafe', 'Talla M', 'TLA-005-1', 320.00, NULL, 12, 5, '{"talla": "M"}'),
    ('textiles-los-andes', 'poncho-de-alpaca-cafe', 'Talla L', 'TLA-005-2', 340.00, NULL, 60, 5, '{"talla": "L"}'),
    ('textiles-los-andes', 'poncho-de-alpaca-cafe', 'Talla XL', 'TLA-005-3', 360.00, NULL, 5, 3, '{"talla": "XL"}'),
    ('textiles-los-andes', 'poncho-de-lana-gris', 'Talla M', 'TLA-006-1', 260.00, 221.00, 3, 3, '{"talla": "M"}'),
    ('textiles-los-andes', 'poncho-de-lana-gris', 'Talla L', 'TLA-006-2', 280.00, NULL, 30, 5, '{"talla": "L"}'),
    ('textiles-los-andes', 'poncho-impermeable-andino', 'Unica', 'TLA-007', 380.00, NULL, 18, 5, '{}'),
    ('textiles-los-andes', 'chalina-de-alpaca', 'Gris', 'TLA-008-1', 95.00, NULL, 0, 3, '{"color": "Gris"}'),
    ('textiles-los-andes', 'chalina-de-alpaca', 'Beige', 'TLA-008-2', 95.00, NULL, 22, 5, '{"color": "Beige"}'),
    ('textiles-los-andes', 'chalina-de-alpaca', 'Vino', 'TLA-008-3', 95.00, 80.75, 7, 3, '{"color": "Vino"}'),
    ('textiles-los-andes', 'chalina-de-baby-alpaca', 'Unica', 'TLA-009', 160.00, NULL, 45, 5, '{}'),
    ('textiles-los-andes', 'bufanda-tejida-a-crochet', 'Unica', 'TLA-010', 70.00, NULL, 10, 5, '{}'),
    ('textiles-los-andes', 'chompa-jacquard-andina', 'S', 'TLA-011-1', 290.00, NULL, 33, 5, '{"talla": "S"}'),
    ('textiles-los-andes', 'chompa-jacquard-andina', 'M', 'TLA-011-2', 300.00, NULL, 4, 3, '{"talla": "M"}'),
    ('textiles-los-andes', 'chompa-jacquard-andina', 'L', 'TLA-011-3', 310.00, 263.50, 27, 5, '{"talla": "L"}'),
    ('textiles-los-andes', 'chompa-de-alpaca-cuello-alto', 'S', 'TLA-012-1', 340.00, NULL, 50, 5, '{"talla": "S"}'),
    ('textiles-los-andes', 'chompa-de-alpaca-cuello-alto', 'M', 'TLA-012-2', 350.00, NULL, 15, 5, '{"talla": "M"}'),
    ('textiles-los-andes', 'chompa-de-alpaca-cuello-alto', 'L', 'TLA-012-3', 360.00, NULL, 40, 5, '{"talla": "L"}'),
    ('textiles-los-andes', 'cardigan-de-lana-natural', 'Unica', 'TLA-013', 300.00, NULL, 8, 3, '{}'),
    ('textiles-los-andes', 'gorro-chullo-con-orejeras', 'Unica', 'TLA-014', 55.00, 46.75, 0, 3, '{}'),
    ('textiles-los-andes', 'gorro-de-alpaca-con-pompon', 'Unica', 'TLA-015', 65.00, NULL, 25, 5, '{}'),
    ('textiles-los-andes', 'vincha-tejida-andina', 'Unica', 'TLA-016', 35.00, NULL, 12, 5, '{}'),
    ('textiles-los-andes', 'guantes-de-lana-tejidos', 'S/M', 'TLA-017-1', 45.00, NULL, 60, 5, '{"talla": "S/M"}'),
    ('textiles-los-andes', 'guantes-de-lana-tejidos', 'L/XL', 'TLA-017-2', 45.00, NULL, 5, 3, '{"talla": "L/XL"}'),
    ('textiles-los-andes', 'medias-de-alpaca-gruesas', 'Unica', 'TLA-018', 40.00, 34.00, 3, 3, '{}'),
    ('textiles-los-andes', 'bolso-tejido-a-mano', 'Unica', 'TLA-019', 130.00, NULL, 30, 5, '{}'),
    ('textiles-los-andes', 'mochila-andina-de-aguayo', 'Unica', 'TLA-020', 180.00, NULL, 18, 5, '{}'),
    ('textiles-los-andes', 'monedero-de-aguayo', 'Unica', 'TLA-021', 35.00, NULL, 0, 3, '{}'),
    ('textiles-los-andes', 'tapiz-decorativo-de-pared', 'Unica', 'TLA-022', 260.00, NULL, 22, 5, '{}'),
    ('textiles-los-andes', 'camino-de-mesa-andino', 'Unica', 'TLA-023', 140.00, 119.00, 7, 3, '{}'),
    ('sabores-de-bolivia', 'cafe-de-altura-yungas-250g', 'Molido', 'SDB-001-1', 55.00, NULL, 45, 5, '{"presentacion": "Molido"}'),
    ('sabores-de-bolivia', 'cafe-de-altura-yungas-250g', 'Grano', 'SDB-001-2', 55.00, NULL, 10, 5, '{"presentacion": "Grano"}'),
    ('sabores-de-bolivia', 'cafe-organico-caranavi-500g', 'Molido', 'SDB-002-1', 110.00, NULL, 33, 5, '{"presentacion": "Molido"}'),
    ('sabores-de-bolivia', 'cafe-organico-caranavi-500g', 'Grano', 'SDB-002-2', 110.00, NULL, 4, 3, '{"presentacion": "Grano"}'),
    ('sabores-de-bolivia', 'cafe-en-grano-espresso-1kg', 'Unica', 'SDB-003', 190.00, 161.50, 27, 5, '{}'),
    ('sabores-de-bolivia', 'cafe-descafeinado-250g', 'Unica', 'SDB-004', 60.00, NULL, 50, 5, '{}'),
    ('sabores-de-bolivia', 'capsulas-de-cafe-compatibles-x10', 'Unica', 'SDB-005', 45.00, NULL, 15, 5, '{}'),
    ('sabores-de-bolivia', 'cafe-soluble-frasco-170g', 'Unica', 'SDB-006', 50.00, NULL, 40, 5, '{}'),
    ('sabores-de-bolivia', 'chocolate-70-cacao-boliviano', 'Unica', 'SDB-007', 28.00, NULL, 8, 3, '{}'),
    ('sabores-de-bolivia', 'chocolate-con-leche-y-quinua', 'Unica', 'SDB-008', 26.00, 22.10, 0, 3, '{}'),
    ('sabores-de-bolivia', 'chocolate-100-cacao-alto-beni', 'Unica', 'SDB-009', 34.00, NULL, 25, 5, '{}'),
    ('sabores-de-bolivia', 'cocoa-en-polvo-200g', 'Unica', 'SDB-010', 32.00, NULL, 12, 5, '{}'),
    ('sabores-de-bolivia', 'bombones-surtidos-caja-x12', 'Unica', 'SDB-011', 55.00, NULL, 60, 5, '{}'),
    ('sabores-de-bolivia', 'mate-de-coca-en-bolsitas-x25', 'Unica', 'SDB-012', 18.00, NULL, 5, 3, '{}'),
    ('sabores-de-bolivia', 'te-de-manzanilla-andina-x25', 'Unica', 'SDB-013', 16.00, 13.60, 3, 3, '{}'),
    ('sabores-de-bolivia', 'infusion-de-muna-40g', 'Unica', 'SDB-014', 22.00, NULL, 30, 5, '{}'),
    ('sabores-de-bolivia', 'anis-de-campo-40g', 'Unica', 'SDB-015', 15.00, NULL, 18, 5, '{}'),
    ('sabores-de-bolivia', 'quinua-pop-con-miel-80g', 'Unica', 'SDB-016', 15.00, NULL, 0, 3, '{}'),
    ('sabores-de-bolivia', 'barras-de-amaranto-x6', 'Unica', 'SDB-017', 24.00, NULL, 22, 5, '{}'),
    ('sabores-de-bolivia', 'mani-tostado-con-sal-200g', 'Unica', 'SDB-018', 18.00, 15.30, 7, 3, '{}'),
    ('sabores-de-bolivia', 'habas-fritas-picantes-150g', 'Unica', 'SDB-019', 16.00, NULL, 45, 5, '{}'),
    ('sabores-de-bolivia', 'chips-de-camote-120g', 'Unica', 'SDB-020', 20.00, NULL, 10, 5, '{}'),
    ('sabores-de-bolivia', 'tostado-de-maiz-willkaparu-250g', 'Unica', 'SDB-021', 17.00, NULL, 33, 5, '{}'),
    ('sabores-de-bolivia', 'miel-de-abeja-pura-500g', 'Unica', 'SDB-022', 45.00, NULL, 4, 3, '{}'),
    ('sabores-de-bolivia', 'azucar-de-cana-integral-1kg', 'Unica', 'SDB-023', 22.00, 18.70, 27, 5, '{}'),
    ('sabores-de-bolivia', 'sal-rosada-de-uyuni-250g', 'Unica', 'SDB-024', 18.00, NULL, 50, 5, '{}'),
    ('sabores-de-bolivia', 'aji-amarillo-molido-100g', 'Unica', 'SDB-025', 15.00, NULL, 15, 5, '{}'),
    ('sabores-de-bolivia', 'quinua-real-blanca-1kg', 'Unica', 'SDB-026', 48.00, NULL, 40, 5, '{}'),
    ('sabores-de-bolivia', 'chia-organica-250g', 'Unica', 'SDB-027', 28.00, NULL, 8, 3, '{}'),
    ('sabores-de-bolivia', 'canahua-en-hojuelas-400g', 'Unica', 'SDB-028', 30.00, 25.50, 0, 3, '{}'),
    ('tecno-oriente', 'funda-de-silicona-para-celular', 'Negro', 'TEC-001-1', 45.00, NULL, 25, 5, '{"color": "Negro"}'),
    ('tecno-oriente', 'funda-de-silicona-para-celular', 'Azul', 'TEC-001-2', 45.00, NULL, 12, 5, '{"color": "Azul"}'),
    ('tecno-oriente', 'funda-de-silicona-para-celular', 'Transparente', 'TEC-001-3', 45.00, NULL, 60, 5, '{"color": "Transparente"}'),
    ('tecno-oriente', 'funda-transparente-antishock', 'Unica', 'TEC-002', 55.00, NULL, 5, 3, '{}'),
    ('tecno-oriente', 'funda-tipo-cartera-con-tarjetero', 'Unica', 'TEC-003', 75.00, 63.75, 3, 3, '{}'),
    ('tecno-oriente', 'vidrio-templado-9h', 'Pack x1', 'TEC-004-1', 25.00, NULL, 30, 5, '{"pack": "1"}'),
    ('tecno-oriente', 'vidrio-templado-9h', 'Pack x2', 'TEC-004-2', 40.00, NULL, 18, 5, '{"pack": "2"}'),
    ('tecno-oriente', 'protector-de-camara-de-vidrio', 'Unica', 'TEC-005', 20.00, NULL, 0, 3, '{}'),
    ('tecno-oriente', 'audifonos-inalambricos-tws', 'Unica', 'TEC-006', 220.00, NULL, 22, 5, '{}'),
    ('tecno-oriente', 'audifonos-con-cable-y-microfono', 'Unica', 'TEC-007', 45.00, 38.25, 7, 3, '{}'),
    ('tecno-oriente', 'audifonos-deportivos-con-gancho', 'Unica', 'TEC-008', 120.00, NULL, 45, 5, '{}'),
    ('tecno-oriente', 'parlante-bluetooth-portatil', 'Unica', 'TEC-009', 180.00, NULL, 10, 5, '{}'),
    ('tecno-oriente', 'parlante-bluetooth-resistente-al-agua', 'Unica', 'TEC-010', 260.00, NULL, 33, 5, '{}'),
    ('tecno-oriente', 'microfono-lavalier-para-celular', 'Unica', 'TEC-011', 90.00, NULL, 4, 3, '{}'),
    ('tecno-oriente', 'cargador-rapido-usb-c-20w', 'Unica', 'TEC-012', 60.00, 51.00, 27, 5, '{}'),
    ('tecno-oriente', 'cargador-de-auto-doble-puerto', 'Unica', 'TEC-013', 55.00, NULL, 50, 5, '{}'),
    ('tecno-oriente', 'power-bank-10000mah', 'Unica', 'TEC-014', 130.00, NULL, 15, 5, '{}'),
    ('tecno-oriente', 'power-bank-20000mah-carga-rapida', 'Unica', 'TEC-015', 210.00, NULL, 40, 5, '{}'),
    ('tecno-oriente', 'cargador-inalambrico-15w', 'Unica', 'TEC-016', 95.00, NULL, 8, 3, '{}'),
    ('tecno-oriente', 'cable-usb-c-a-usb-c-1m', '1 metro', 'TEC-017-1', 25.00, 21.25, 0, 3, '{"largo": "1m"}'),
    ('tecno-oriente', 'cable-usb-c-a-usb-c-1m', '2 metros', 'TEC-017-2', 35.00, NULL, 25, 5, '{"largo": "2m"}'),
    ('tecno-oriente', 'cable-lightning-trenzado-2m', 'Unica', 'TEC-018', 40.00, NULL, 12, 5, '{}'),
    ('tecno-oriente', 'cable-usb-c-a-hdmi-4k', 'Unica', 'TEC-019', 85.00, NULL, 60, 5, '{}'),
    ('tecno-oriente', 'memoria-usb-64gb', 'Unica', 'TEC-020', 55.00, NULL, 5, 3, '{}'),
    ('tecno-oriente', 'microsd-128gb-clase-10', 'Unica', 'TEC-021', 95.00, 80.75, 3, 3, '{}'),
    ('tecno-oriente', 'hub-usb-c-6-en-1', 'Unica', 'TEC-022', 160.00, NULL, 30, 5, '{}'),
    ('tecno-oriente', 'smartwatch-deportivo', 'Negro', 'TEC-023-1', 320.00, NULL, 18, 5, '{"color": "Negro"}'),
    ('tecno-oriente', 'smartwatch-deportivo', 'Plata', 'TEC-023-2', 330.00, NULL, 0, 3, '{"color": "Plata"}'),
    ('tecno-oriente', 'banda-de-actividad-fisica', 'Unica', 'TEC-024', 150.00, NULL, 22, 5, '{}'),
    ('tecno-oriente', 'soporte-de-celular-para-auto', 'Unica', 'TEC-025', 60.00, 51.00, 7, 3, '{}'),
    ('tecno-oriente', 'aro-de-luz-led-10-pulgadas', 'Unica', 'TEC-026', 110.00, NULL, 45, 5, '{}'),
    ('tecno-oriente', 'tripode-flexible-para-celular', 'Unica', 'TEC-027', 45.00, NULL, 10, 5, '{}'),
    ('tecno-oriente', 'gamepad-bluetooth', 'Unica', 'TEC-028', 140.00, NULL, 33, 5, '{}'),
    ('tecno-oriente', 'mouse-inalambrico', 'Unica', 'TEC-029', 70.00, NULL, 4, 3, '{}'),
    ('tecno-oriente', 'teclado-bluetooth-compacto', 'Unica', 'TEC-030', 160.00, 136.00, 27, 5, '{}'),
    ('tecno-oriente', 'foco-inteligente-wifi-rgb', 'Unica', 'TEC-031', 65.00, NULL, 50, 5, '{}'),
    ('tecno-oriente', 'enchufe-inteligente-wifi', 'Unica', 'TEC-032', 70.00, NULL, 15, 5, '{}'),
    ('ceramica-tiwanaku', 'juego-de-tazas-andinas-x4', 'Unica', 'CTW-001', 140.00, NULL, 40, 5, '{}'),
    ('ceramica-tiwanaku', 'juego-de-platos-esmaltados-x6', 'Unica', 'CTW-002', 260.00, NULL, 8, 3, '{}'),
    ('ceramica-tiwanaku', 'bowl-de-ceramica-rustica', 'Chico', 'CTW-003-1', 45.00, 38.25, 0, 3, '{"tamano": "Chico"}'),
    ('ceramica-tiwanaku', 'bowl-de-ceramica-rustica', 'Grande', 'CTW-003-2', 65.00, NULL, 25, 5, '{"tamano": "Grande"}'),
    ('ceramica-tiwanaku', 'ensaladera-grande-pintada', 'Unica', 'CTW-004', 120.00, NULL, 12, 5, '{}'),
    ('ceramica-tiwanaku', 'fuente-ovalada-para-horno', 'Unica', 'CTW-005', 110.00, NULL, 60, 5, '{}'),
    ('ceramica-tiwanaku', 'jarra-de-agua-1-5l', 'Unica', 'CTW-006', 95.00, NULL, 5, 3, '{}'),
    ('ceramica-tiwanaku', 'set-de-jarro-y-vasos-x4', 'Unica', 'CTW-007', 150.00, 127.50, 3, 3, '{}'),
    ('ceramica-tiwanaku', 'taza-mug-artesanal', 'Azul', 'CTW-008-1', 40.00, NULL, 30, 5, '{"color": "Azul"}'),
    ('ceramica-tiwanaku', 'taza-mug-artesanal', 'Verde', 'CTW-008-2', 40.00, NULL, 18, 5, '{"color": "Verde"}'),
    ('ceramica-tiwanaku', 'taza-mug-artesanal', 'Terracota', 'CTW-008-3', 40.00, NULL, 0, 3, '{"color": "Terracota"}'),
    ('ceramica-tiwanaku', 'taza-espresso-x2', 'Unica', 'CTW-009', 55.00, NULL, 22, 5, '{}'),
    ('ceramica-tiwanaku', 'chop-cervecero-de-ceramica', 'Unica', 'CTW-010', 60.00, 51.00, 7, 3, '{}'),
    ('ceramica-tiwanaku', 'plato-decorativo-tiwanaku', 'Mediano', 'CTW-011-1', 85.00, NULL, 45, 5, '{"tamano": "Mediano"}'),
    ('ceramica-tiwanaku', 'plato-decorativo-tiwanaku', 'Grande', 'CTW-011-2', 130.00, NULL, 10, 5, '{"tamano": "Grande"}'),
    ('ceramica-tiwanaku', 'cuadro-ceramico-puerta-del-sol', 'Unica', 'CTW-012', 190.00, NULL, 33, 5, '{}'),
    ('ceramica-tiwanaku', 'figura-de-chakana', 'Unica', 'CTW-013', 70.00, NULL, 4, 3, '{}'),
    ('ceramica-tiwanaku', 'portavelas-de-ceramica-x3', 'Unica', 'CTW-014', 60.00, 51.00, 27, 5, '{}'),
    ('ceramica-tiwanaku', 'campana-de-viento-de-ceramica', 'Unica', 'CTW-015', 55.00, NULL, 50, 5, '{}'),
    ('ceramica-tiwanaku', 'florero-de-ceramica-esmaltada', 'Unica', 'CTW-016', 95.00, NULL, 15, 5, '{}'),
    ('ceramica-tiwanaku', 'florero-alto-minimalista', 'Unica', 'CTW-017', 120.00, NULL, 40, 5, '{}'),
    ('ceramica-tiwanaku', 'set-de-3-mini-floreros', 'Unica', 'CTW-018', 80.00, NULL, 8, 3, '{}'),
    ('ceramica-tiwanaku', 'maceta-de-barro-pintada-a-mano', 'Chica', 'CTW-019-1', 35.00, 29.75, 0, 3, '{"tamano": "Chica"}'),
    ('ceramica-tiwanaku', 'maceta-de-barro-pintada-a-mano', 'Mediana', 'CTW-019-2', 55.00, NULL, 25, 5, '{"tamano": "Mediana"}'),
    ('ceramica-tiwanaku', 'maceta-de-barro-pintada-a-mano', 'Grande', 'CTW-019-3', 80.00, NULL, 12, 5, '{"tamano": "Grande"}'),
    ('ceramica-tiwanaku', 'maceta-colgante-trenzada', 'Unica', 'CTW-020', 65.00, NULL, 60, 5, '{}'),
    ('ceramica-tiwanaku', 'set-de-macetas-pequenas-x3', 'Unica', 'CTW-021', 90.00, NULL, 5, 3, '{}'),
    ('ceramica-tiwanaku', 'maceta-grande-para-exterior', 'Unica', 'CTW-022', 130.00, 110.50, 3, 3, '{}'),
    ('ceramica-tiwanaku', 'lampara-de-mesa-de-ceramica', 'Unica', 'CTW-023', 220.00, NULL, 30, 5, '{}'),
    ('ceramica-tiwanaku', 'aplique-de-pared-artesanal', 'Unica', 'CTW-024', 140.00, NULL, 18, 5, '{}'),
    ('ceramica-tiwanaku', 'individuales-de-ceramica-x4', 'Unica', 'CTW-025', 70.00, NULL, 0, 3, '{}'),
    ('ceramica-tiwanaku', 'salero-y-pimentero', 'Unica', 'CTW-026', 45.00, NULL, 22, 5, '{}'),
    ('ceramica-tiwanaku', 'aceitera-de-ceramica', 'Unica', 'CTW-027', 50.00, 42.50, 7, 3, '{}'),
    ('ceramica-tiwanaku', 'mortero-de-piedra-volcanica', 'Unica', 'CTW-028', 85.00, NULL, 45, 5, '{}'),
    ('ceramica-tiwanaku', 'difusor-de-aromas-de-ceramica', 'Unica', 'CTW-029', 75.00, NULL, 10, 5, '{}'),
    ('ceramica-tiwanaku', 'quemador-de-incienso-artesanal', 'Unica', 'CTW-030', 40.00, NULL, 33, 5, '{}')
) AS d(slug, pslug, vnombre, sku, precio, precio_oferta, stock, stock_minimo, atributos)
WHERE NOT EXISTS (
    SELECT 1 FROM variante v
    WHERE v.producto_id = (
              SELECT p.id FROM producto p
              WHERE p.tienda_id = (SELECT id FROM tienda WHERE slug = d.slug)
                AND p.slug = d.pslug
              LIMIT 1)
      AND v.sku = d.sku
);

-- 8. Resumen
SELECT
    (SELECT count(*) FROM usuario WHERE email IN ('empresa1@kantu.bo', 'empresa2@kantu.bo', 'empresa3@kantu.bo', 'empresa4@kantu.bo')) AS empresas,
    (SELECT count(*) FROM tienda WHERE slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku')) AS tiendas,
    (SELECT count(*) FROM categoria c JOIN tienda t ON t.id = c.tienda_id
        WHERE t.slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku')) AS categorias,
    (SELECT count(*) FROM producto p JOIN tienda t ON t.id = p.tienda_id
        WHERE t.slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku')) AS productos,
    (SELECT count(*) FROM variante v
        JOIN producto p ON p.id = v.producto_id
        JOIN tienda t ON t.id = p.tienda_id
        WHERE t.slug IN ('textiles-los-andes', 'sabores-de-bolivia', 'tecno-oriente', 'ceramica-tiwanaku')) AS variantes;

COMMIT;
