# Generated by Django 5.1.9 on 2026-08-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('tiendas', '0004_direcciontienda_usuariotienda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('segmento_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='crm.segmento')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'campana',
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('tipo_descuento', models.CharField(max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_expiracion', models.DateField()),
                ('usos_maximos', models.IntegerField(default=1)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to='marketing.campana')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'db_table': 'cupon',
            },
        ),
        migrations.CreateModel(
            name='CuponUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='marketing.cupon')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_cupon', to='pedidos.pedido')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_cupones', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Uso de Cupón',
                'verbose_name_plural': 'Usos de Cupones',
                'db_table': 'cupon_uso',
                'ordering': ['-fecha_uso'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_entrega', models.CharField(max_length=20)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='marketing.campana')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Notificación Enviada',
                'verbose_name_plural': 'Notificaciones Enviadas',
                'db_table': 'notificacion_enviada',
                'ordering': ['-fecha'],
            },
        ),
    ]
