# Generated by Django 5.1.9 on 2026-09-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_migrar_datos_cu08'),
        ('pedidos', '0002_alter_itemcarrito_variante_alter_itempedido_variante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributo',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='varianteatributo',
            name='atributo',
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='productoetiqueta',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='productoetiqueta',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productoetiqueta',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='varianteatributo',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='varianteatributo',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='precio_adicional',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='tienda',
        ),
        migrations.AlterField(
            model_name='variante',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='variante',
            name='sku',
            field=models.CharField(max_length=60),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='variante_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.CheckConstraint(condition=models.Q(('precio_oferta__isnull', True), ('precio_oferta__gte', 0), _connector='OR'), name='variante_precio_oferta_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='variante_stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='variante_stock_minimo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(fields=('producto', 'sku'), name='variante_producto_sku_unico'),
        ),
        migrations.DeleteModel(
            name='Atributo',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='ProductoEtiqueta',
        ),
        migrations.DeleteModel(
            name='VarianteAtributo',
        ),
    ]
