# Generated by Django 5.1.9 on 2026-08-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
