# Generated by Django 5.1.9 on 2026-08-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0003_alter_tienda_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Dirección de Tienda',
                'verbose_name_plural': 'Direcciones de Tiendas',
                'db_table': 'direccion_tienda',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_interno', models.CharField(max_length=30)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_tienda', to='tiendas.tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_tiendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Tienda',
                'verbose_name_plural': 'Usuarios Tiendas',
                'db_table': 'usuario_tienda',
                'unique_together': {('usuario', 'tienda')},
            },
        ),
    ]
