# Generated by Django 5.1.9 on 2026-08-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('tiendas', '0004_direcciontienda_usuariotienda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_cliente', to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_cliente', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Ficha de Cliente',
                'verbose_name_plural': 'Fichas de Clientes',
                'db_table': 'ficha_cliente',
            },
        ),
        migrations.CreateModel(
            name='InteraccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('ficha_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='crm.fichacliente')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_cliente', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Interacción con Cliente',
                'verbose_name_plural': 'Interacciones con Clientes',
                'db_table': 'interaccion_cliente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ficha_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_deseos', to='crm.fichacliente')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_deseos', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Lista de Deseos',
                'verbose_name_plural': 'Listas de Deseos',
                'db_table': 'lista_deseos',
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('criterio', models.CharField(max_length=150)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
                'db_table': 'segmento',
            },
        ),
        migrations.AddField(
            model_name='fichacliente',
            name='segmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_cliente', to='crm.segmento'),
        ),
        migrations.CreateModel(
            name='ItemListaDeseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_listas_deseos', to='catalogo.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_lista_deseos', to='tiendas.tienda')),
                ('lista_deseos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.listadeseos')),
            ],
            options={
                'verbose_name': 'Ítem de Lista de Deseos',
                'verbose_name_plural': 'Ítems de Listas de Deseos',
                'db_table': 'item_lista_deseos',
                'unique_together': {('lista_deseos', 'producto')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='fichacliente',
            unique_together={('cliente', 'tienda')},
        ),
    ]
