# Generated by Django 5.1.9 on 2026-08-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0004_direcciontienda_usuariotienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'db_table': 'atributo',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalogo.categoria')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'etiqueta',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, default='', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.categoria')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='tiendas.tienda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'db_table': 'imagen_producto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variante', models.CharField(max_length=100)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sku_variante', models.CharField(blank=True, default='', max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes_producto', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'db_table': 'variante_producto',
            },
        ),
        migrations.CreateModel(
            name='VarianteAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes_atributos', to='catalogo.atributo')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes_atributos', to='tiendas.tienda')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes_atributos', to='catalogo.varianteproducto')),
            ],
            options={
                'verbose_name': 'Variante Atributo',
                'verbose_name_plural': 'Variantes Atributos',
                'db_table': 'variante_atributo',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('umbral_minimo', models.IntegerField(default=5)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='tiendas.tienda')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='catalogo.varianteproducto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='ProductoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_etiquetas', to='catalogo.etiqueta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_etiquetas', to='catalogo.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_etiquetas', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Producto Etiqueta',
                'verbose_name_plural': 'Productos Etiquetas',
                'db_table': 'producto_etiqueta',
                'unique_together': {('producto', 'etiqueta')},
            },
        ),
    ]
