# Generated by Django 5.1.9 on 2026-09-05 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_esquema_transitorio_cu08'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carritos', to='catalogo.variante'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='catalogo.variante'),
        ),
    ]
