# Generated by Django 5.1.9 on 2026-09-06 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_permiso_logauditoria_rolpermiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraacceso',
            name='email_intento',
            field=models.EmailField(blank=True, default='', help_text='Email tal como se envió en el intento de login.', max_length=254, verbose_name='email del intento'),
        ),
        migrations.AddField(
            model_name='bitacoraacceso',
            name='exitoso',
            field=models.BooleanField(default=True, verbose_name='inicio de sesión exitoso'),
        ),
        migrations.AddField(
            model_name='bitacoraacceso',
            name='motivo',
            field=models.CharField(blank=True, default='', help_text='Solo se completa cuando exitoso=False.', max_length=100, verbose_name='motivo del rechazo'),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='NULL si el intento fue con un email que no existe.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_accesos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bitacoraacceso',
            index=models.Index(fields=['-fecha'], name='bitacora_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacoraacceso',
            index=models.Index(fields=['usuario', '-fecha'], name='bitacora_usuario_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacoraacceso',
            index=models.Index(fields=['exitoso', '-fecha'], name='bitacora_exitoso_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['-fecha'], name='logaud_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['tabla_afectada', 'accion'], name='logaud_tabla_accion_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', '-fecha'], name='logaud_usuario_fecha_idx'),
        ),
    ]
